version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
      - "2222:22" # SSH port mapping
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=web_app.main
      - DATABASE_URL=postgresql://user:password@db:5432/lyricsdb
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lyricsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d lyricsdb"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
